# Generated by Django 5.1.6 on 2025-04-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
