# Generated by Django 5.1.6 on 2025-04-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_fanfavoritevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfavoritevote',
            name='fan_votes',
            field=models.IntegerField(default=0),
        ),
    ]
