# Generated by Django 5.1.6 on 2025-04-12 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_fanfavoritevote_fan_votes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fanfavoritevote',
            unique_together={('user', 'profile')},
        ),
        migrations.RemoveField(
            model_name='fanfavoritevote',
            name='fan_votes',
        ),
    ]
